/**
 * faq-i18n.js — FAQ questions & answers in EN / RU / EL
 *
 * The FAQ copy is large and markup-heavy (paragraphs, lists, <strong>), so it
 * lives here instead of translations.js. Answers use the `data-i18n-html`
 * attribute (innerHTML) so their formatting is preserved; questions use plain
 * `data-i18n`. This file must load AFTER translations.js (so `T` exists) and
 * BEFORE main.js (so the keys are present when applyTranslations first runs).
 */
(function () {
  if (typeof T === 'undefined') return;

  const faq = {
    en: {
      'faq.q1': `What exactly is an off-grid solar system?`,
      'faq.q2': `Is off-grid solar reliable enough for full-time living?`,
      'faq.q3': `How do I know what size system I need?`,
      'faq.q4': `What happens at night or on consecutive cloudy days?`,
      'faq.q5': `How long do the batteries last?`,
      'faq.q6': `Can I monitor and control my system remotely?`,
      'faq.q7': `How long does the whole process take — from first contact to a live system?`,
      'faq.q8': `Do you install internationally? Can you come to my country?`,
      'faq.q9': `Do I need planning permission or permits for an off-grid system?`,
      'faq.q10': `How much does an off-grid solar system cost?`,
      'faq.q11': `What does your 7-year warranty cover?`,
      'faq.q12': `Do you offer financing or payment plans?`,

      'faq.a1': `<p>An off-grid solar system is a completely standalone power setup that generates, stores, and delivers electricity independently of the utility grid. There is no monthly electricity bill, no blackout risk from grid failures, and no reliance on a utility provider.</p><p>The core components are: <strong class="text-slate-300">solar PV panels</strong> that harvest sunlight, a <strong class="text-slate-300">lithium battery bank</strong> that stores energy for nights and cloudy days, an <strong class="text-slate-300">MPPT charge controller</strong> that optimises the harvest, and a <strong class="text-slate-300">hybrid inverter</strong> that converts stored DC energy to standard AC power for your appliances.</p><p>Every system we design is engineered to cover 365 days a year — including winter months and consecutive overcast days — without any fuel or grid input.</p>`,
      'faq.a2': `<p>Yes — our systems achieve <strong class="text-slate-300">99.9% measured uptime</strong> across our installed base. Hundreds of families, farms, and businesses worldwide live entirely on our systems with no grid connection whatsoever.</p><p>Reliability comes from proper sizing and redundancy. We model your specific location's solar irradiance data (at least 10 years of records) and design battery capacity to cover at least 3–5 consecutive days of zero solar input, depending on your latitude and season.</p><p>Optional backup generators can be integrated with automatic start logic for extreme conditions, though most clients never need to activate them.</p>`,
      'faq.a3': `<p>System sizing depends on three key factors: your <strong class="text-slate-300">daily energy consumption</strong> (in kWh), your <strong class="text-slate-300">geographic location</strong> (peak sun hours), and your <strong class="text-slate-300">peak load requirements</strong> (the maximum watts all devices could draw simultaneously).</p><p>As a rough guide: a modern 3-bedroom home typically needs 8–15 kWp of panels and 20–40 kWh of battery storage. A large farm may need 30–60 kWp. A remote cabin might need only 2–5 kWp.</p><p>We include a <strong class="text-slate-300">free detailed energy audit and sizing report</strong> with every quote. Send us your details via the contact form and our engineers will produce an accurate specification within 24 hours.</p>`,
      'faq.a4': `<p>At night, your <strong class="text-slate-300">lithium battery bank</strong> takes over seamlessly — the inverter continues delivering stable AC power with zero interruption. The transition is instantaneous and invisible to your appliances.</p><p>On cloudy days, panels still produce 10–30% of their rated output (depending on cloud density). The battery covers the deficit. We size the battery to handle your worst-case seasonal scenario with at least 3 days of autonomy — meaning 3 full days of zero solar input at your normal consumption level.</p><p>If you opt for an <strong class="text-slate-300">integrated generator</strong>, it will auto-start only when the battery state of charge drops below a configurable threshold (typically 20%), top it up, and shut off — all without any manual intervention.</p>`,
      'faq.a5': `<p>We specify <strong class="text-slate-300">LiFePO₄ (lithium iron phosphate)</strong> batteries exclusively — the safest, most durable chemistry available. At a typical daily cycle, these batteries last <strong class="text-slate-300">10–15 years</strong>, rated for 6,000+ full charge cycles to 80% capacity.</p><p>This is dramatically better than traditional lead-acid batteries (3–5 years) and safer than other lithium chemistries (no thermal runaway risk). Every pack comes from tier-1 manufacturers with built-in Battery Management Systems (BMS) that protect against overcharge, over-discharge, and temperature extremes.</p><p>Batteries are covered under our 7-year comprehensive warranty and come with a manufacturer performance guarantee of 10+ years.</p>`,
      'faq.a6': `<p>Yes — every system includes a <strong class="text-slate-300">smart monitoring platform</strong> accessible via smartphone, tablet, or browser. You can see real-time solar production, battery state of charge, load consumption, and historical data from anywhere in the world.</p><p>The <strong class="text-slate-300">monitoring portal</strong> (web + app) can send automatic alerts by email or SMS if any parameter falls outside normal ranges.</p><p>Our engineers also have remote diagnostic access — we can troubleshoot and often resolve issues without a site visit, saving you time and cost.</p>`,
      'faq.a7': `<p>The typical timeline from initial inquiry to a commissioned system is <strong class="text-slate-300">6–14 weeks</strong>, depending on system size and location. Here is how it breaks down:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Week 1–2:</strong> Free site analysis, energy audit, and custom system design</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Week 2–3:</strong> Detailed quote delivery, revisions, and contract signing</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Week 3–8:</strong> Equipment procurement and logistics to site</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Week 8–12:</strong> Installation, commissioning, and system handover</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Ongoing:</strong> Remote monitoring, annual check-up, lifetime support</span></li></ul><p>Smaller cabin systems can be completed in as little as 4 weeks. Large commercial projects may run to 16–20 weeks.</p>`,
      'faq.a8': `<p>Yes — we operate across <strong class="text-slate-300">40+ countries</strong> through our certified partner installation network. We have completed projects on six continents, from alpine properties to island resorts.</p><p>For most countries, we deploy a local certified partner who handles on-site installation under our direct engineering supervision. For complex or large projects, our own engineers travel to the site for commissioning.</p><p>We manage all international logistics, customs documentation, and local compliance requirements on your behalf. Just tell us where your site is located when you submit your quote request.</p>`,
      'faq.a9': `<p>Planning requirements <strong class="text-slate-300">vary significantly by country, region, and system size</strong>. In many jurisdictions, rooftop or ground-mounted systems below a certain kWp threshold are exempt from planning permission. Larger systems and ground arrays more commonly require permits.</p><p>As a pure off-grid system (no grid connection), you typically avoid the most complex grid-connection regulations. However, structural permits for mounting structures and building regulations for electrical installations still apply in most countries.</p><p><strong class="text-slate-300">We handle all permitting research and documentation as part of our full turnkey service.</strong> Our local partners are familiar with the regulations in their regions, and our team will guide you through every requirement relevant to your site before any work begins.</p>`,
      'faq.a10': `<p>Costs vary widely based on system size, components, location, and installation complexity. Here are indicative ranges for fully installed, turnkey systems:</p><div class="mt-3 space-y-2"><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Remote Cabin (WildPower Kit)</span><span class="text-brand-400 font-bold text-sm">€6,000 – €18,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Residential (HomeBase Pro)</span><span class="text-brand-400 font-bold text-sm">€22,000 – €65,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Farm / Rural (AgroGrid Elite)</span><span class="text-brand-400 font-bold text-sm">€55,000 – €180,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Commercial (IndustrialCore)</span><span class="text-brand-400 font-bold text-sm">From €120,000+</span></div></div><p class="mt-3">These are full turnkey prices including design, equipment, shipping, installation, commissioning, and 7-year warranty. A <strong class="text-slate-300">detailed itemised quote is always free</strong> — submit your details and our engineers will provide exact pricing for your specific project.</p>`,
      'faq.a11': `<p>Our <strong class="text-slate-300">7-year comprehensive system warranty</strong> is one of the broadest in the industry. It covers:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>All major components: solar panels, battery bank, inverter/charger, charge controller</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>All wiring, connectors, and mounting hardware</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Installation workmanship and commissioning quality</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Software, firmware, and monitoring platform access</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Remote diagnostics and troubleshooting at no extra cost</span></li></ul><p class="mt-2">On top of our system warranty, panels carry a <strong class="text-slate-300">25-year performance guarantee</strong> from the manufacturer (typically ≥80% output at year 25). After your 7-year warranty period, we offer affordable annual O&M (operations &amp; maintenance) contracts for continued support.</p>`,
      'faq.a12': `<p>Yes — we work with several <strong class="text-slate-300">green energy financing partners</strong> to offer flexible payment options for qualified clients. Depending on your country and project size, options may include:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Stage-payment contracts (deposit on order, balance on commissioning)</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Green energy loans through partner financial institutions</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Leasing arrangements for commercial and agricultural projects</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Guidance on government grants and subsidy programmes in your country</span></li></ul><p class="mt-2">Financing availability varies by region. <strong class="text-slate-300">Ask about financing options when you submit your quote request</strong> — our team will outline what's available for your specific location and project scale.</p>`,
    },

    ru: {
      'faq.q1': `Что такое автономная солнечная система?`,
      'faq.q2': `Достаточно ли надёжна автономная солнечная энергия для постоянного проживания?`,
      'faq.q3': `Как понять, какого размера система мне нужна?`,
      'faq.q4': `Что происходит ночью или в несколько пасмурных дней подряд?`,
      'faq.q5': `Сколько служат аккумуляторы?`,
      'faq.q6': `Можно ли контролировать систему удалённо?`,
      'faq.q7': `Сколько времени занимает весь процесс — от первого контакта до работающей системы?`,
      'faq.q8': `Устанавливаете ли вы за рубежом? Можете приехать в мою страну?`,
      'faq.q9': `Нужно ли разрешение или согласования для автономной системы?`,
      'faq.q10': `Сколько стоит автономная солнечная система?`,
      'faq.q11': `Что покрывает ваша 7-летняя гарантия?`,
      'faq.q12': `Предлагаете ли вы финансирование или рассрочку?`,

      'faq.a1': `<p>Автономная солнечная система — это полностью самостоятельный источник питания, который генерирует, хранит и подаёт электроэнергию независимо от общей электросети. Никаких ежемесячных счетов за электричество, никакого риска отключений из-за аварий в сети и никакой зависимости от поставщика.</p><p>Основные компоненты: <strong class="text-slate-300">солнечные фотоэлектрические панели</strong>, собирающие солнечный свет, <strong class="text-slate-300">литиевый аккумуляторный банк</strong>, хранящий энергию для ночи и пасмурных дней, <strong class="text-slate-300">MPPT-контроллер заряда</strong>, оптимизирующий выработку, и <strong class="text-slate-300">гибридный инвертор</strong>, преобразующий накопленную энергию постоянного тока в стандартный переменный ток для ваших приборов.</p><p>Каждая система, которую мы проектируем, рассчитана на работу 365 дней в году — включая зимние месяцы и несколько пасмурных дней подряд — без топлива и подключения к сети.</p>`,
      'faq.a2': `<p>Да — наши системы обеспечивают <strong class="text-slate-300">99,9% измеренного времени безотказной работы</strong> по всему парку установок. Сотни семей, ферм и предприятий по всему миру живут полностью на наших системах без какого-либо подключения к сети.</p><p>Надёжность достигается за счёт правильного расчёта и резервирования. Мы моделируем данные солнечной инсоляции для вашей конкретной локации (минимум за 10 лет наблюдений) и рассчитываем ёмкость аккумуляторов на как минимум 3–5 дней подряд при нулевой выработке, в зависимости от широты и сезона.</p><p>При необходимости можно интегрировать резервные генераторы с автоматическим запуском для экстремальных условий, хотя большинству клиентов они никогда не требуются.</p>`,
      'faq.a3': `<p>Расчёт системы зависит от трёх ключевых факторов: вашего <strong class="text-slate-300">суточного потребления энергии</strong> (в кВт·ч), <strong class="text-slate-300">географического расположения</strong> (пиковые солнечные часы) и <strong class="text-slate-300">пиковой нагрузки</strong> (максимальная мощность, которую все устройства могут потреблять одновременно).</p><p>Ориентировочно: современному дому с 3 спальнями обычно требуется 8–15 кВт панелей и 20–40 кВт·ч аккумуляторов. Крупной ферме может понадобиться 30–60 кВт. Удалённому домику — всего 2–5 кВт.</p><p>С каждым коммерческим предложением мы включаем <strong class="text-slate-300">бесплатный подробный энергоаудит и отчёт по расчёту</strong>. Отправьте нам данные через форму связи, и наши инженеры подготовят точную спецификацию в течение 24 часов.</p>`,
      'faq.a4': `<p>Ночью управление плавно берёт на себя ваш <strong class="text-slate-300">литиевый аккумуляторный банк</strong> — инвертор продолжает подавать стабильный переменный ток без каких-либо перерывов. Переход мгновенный и незаметный для приборов.</p><p>В пасмурные дни панели по-прежнему вырабатывают 10–30% номинальной мощности (в зависимости от плотности облаков). Дефицит покрывает аккумулятор. Мы рассчитываем ёмкость на худший сезонный сценарий с автономией не менее 3 дней — то есть 3 полных дня нулевой выработки при вашем обычном уровне потребления.</p><p>Если вы выберете <strong class="text-slate-300">встроенный генератор</strong>, он запустится автоматически только когда заряд аккумулятора опустится ниже настраиваемого порога (обычно 20%), подзарядит его и отключится — полностью без ручного вмешательства.</p>`,
      'faq.a5': `<p>Мы используем исключительно аккумуляторы <strong class="text-slate-300">LiFePO₄ (литий-железо-фосфат)</strong> — самую безопасную и долговечную из доступных химий. При типичном ежедневном цикле такие аккумуляторы служат <strong class="text-slate-300">10–15 лет</strong> и рассчитаны на 6000+ полных циклов заряда до 80% ёмкости.</p><p>Это значительно лучше традиционных свинцово-кислотных аккумуляторов (3–5 лет) и безопаснее других литиевых химий (нет риска теплового разгона). Каждый блок поставляется от производителей первого эшелона со встроенной системой управления батареей (BMS), защищающей от перезаряда, переразряда и температурных экстремумов.</p><p>Аккумуляторы покрываются нашей комплексной 7-летней гарантией и имеют гарантию производительности от производителя на 10+ лет.</p>`,
      'faq.a6': `<p>Да — каждая система включает <strong class="text-slate-300">умную платформу мониторинга</strong>, доступную со смартфона, планшета или браузера. Вы видите выработку в реальном времени, уровень заряда аккумулятора, потребление нагрузки и историю данных из любой точки мира.</p><p><strong class="text-slate-300">Портал мониторинга</strong> (веб + приложение) может отправлять автоматические уведомления по электронной почте или SMS, если любой параметр выходит за нормальные пределы.</p><p>У наших инженеров также есть удалённый доступ для диагностики — мы можем выявлять и часто устранять проблемы без выезда на объект, экономя ваше время и деньги.</p>`,
      'faq.a7': `<p>Обычный срок от первого обращения до введённой в эксплуатацию системы составляет <strong class="text-slate-300">6–14 недель</strong>, в зависимости от размера и расположения. Вот как это распределяется:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Неделя 1–2:</strong> бесплатный анализ объекта, энергоаудит и индивидуальное проектирование</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Неделя 2–3:</strong> предоставление подробного предложения, правки и подписание договора</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Неделя 3–8:</strong> закупка оборудования и доставка на объект</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Неделя 8–12:</strong> монтаж, ввод в эксплуатацию и передача системы</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Далее:</strong> удалённый мониторинг, ежегодная проверка, пожизненная поддержка</span></li></ul><p>Небольшие системы для домиков можно завершить всего за 4 недели. Крупные коммерческие проекты могут занять 16–20 недель.</p>`,
      'faq.a8': `<p>Да — мы работаем в <strong class="text-slate-300">более чем 40 странах</strong> через сеть сертифицированных партнёров по монтажу. Мы реализовали проекты на шести континентах — от горных объектов до островных курортов.</p><p>Для большинства стран мы привлекаем местного сертифицированного партнёра, который выполняет монтаж на объекте под нашим непосредственным инженерным контролем. Для сложных или крупных проектов на объект для ввода в эксплуатацию выезжают наши собственные инженеры.</p><p>Мы берём на себя всю международную логистику, таможенную документацию и требования локального соответствия. Просто укажите расположение вашего объекта при отправке запроса.</p>`,
      'faq.a9': `<p>Требования к согласованиям <strong class="text-slate-300">существенно различаются по странам, регионам и размеру системы</strong>. Во многих юрисдикциях крышные или наземные системы ниже определённого порога по кВт освобождены от разрешения на строительство. Более крупные системы и наземные массивы чаще требуют разрешений.</p><p>Как чисто автономная система (без подключения к сети) вы обычно избегаете самых сложных правил сетевого подключения. Однако конструктивные разрешения на монтажные конструкции и строительные нормы для электроустановок в большинстве стран по-прежнему применяются.</p><p><strong class="text-slate-300">Мы берём на себя все исследования и документацию по согласованиям в рамках нашего полного сервиса «под ключ».</strong> Наши местные партнёры знакомы с нормами своих регионов, и наша команда проведёт вас через все требования, относящиеся к вашему объекту, до начала любых работ.</p>`,
      'faq.a10': `<p>Стоимость сильно зависит от размера системы, компонентов, расположения и сложности монтажа. Вот ориентировочные диапазоны для полностью установленных систем «под ключ»:</p><div class="mt-3 space-y-2"><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Удалённый домик (WildPower Kit)</span><span class="text-brand-400 font-bold text-sm">€6,000 – €18,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Жилой дом (HomeBase Pro)</span><span class="text-brand-400 font-bold text-sm">€22,000 – €65,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Ферма / село (AgroGrid Elite)</span><span class="text-brand-400 font-bold text-sm">€55,000 – €180,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Коммерческий (IndustrialCore)</span><span class="text-brand-400 font-bold text-sm">от €120,000+</span></div></div><p class="mt-3">Это полные цены «под ключ», включая проектирование, оборудование, доставку, монтаж, ввод в эксплуатацию и 7-летнюю гарантию. <strong class="text-slate-300">Подробное детализированное предложение всегда бесплатно</strong> — отправьте свои данные, и наши инженеры предоставят точную стоимость для вашего проекта.</p>`,
      'faq.a11': `<p>Наша <strong class="text-slate-300">комплексная 7-летняя гарантия на систему</strong> — одна из самых широких в отрасли. Она покрывает:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Все основные компоненты: солнечные панели, аккумуляторный банк, инвертор/зарядное устройство, контроллер заряда</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Всю проводку, разъёмы и монтажное оборудование</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Качество монтажа и ввода в эксплуатацию</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Программное обеспечение, прошивку и доступ к платформе мониторинга</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Удалённую диагностику и устранение неполадок без дополнительной платы</span></li></ul><p class="mt-2">Помимо гарантии на систему, панели имеют <strong class="text-slate-300">25-летнюю гарантию производительности</strong> от производителя (обычно ≥80% выработки к 25-му году). После 7-летнего гарантийного периода мы предлагаем доступные ежегодные контракты на обслуживание (O&amp;M) для дальнейшей поддержки.</p>`,
      'faq.a12': `<p>Да — мы сотрудничаем с несколькими <strong class="text-slate-300">партнёрами по финансированию зелёной энергетики</strong>, чтобы предложить гибкие варианты оплаты для подходящих клиентов. В зависимости от страны и размера проекта варианты могут включать:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Поэтапную оплату (аванс при заказе, остаток при вводе в эксплуатацию)</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Кредиты на зелёную энергетику через партнёрские финансовые организации</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Лизинговые схемы для коммерческих и сельскохозяйственных проектов</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Консультации по государственным грантам и программам субсидий в вашей стране</span></li></ul><p class="mt-2">Доступность финансирования зависит от региона. <strong class="text-slate-300">Спросите о вариантах финансирования при отправке запроса</strong> — наша команда расскажет, что доступно для вашего расположения и масштаба проекта.</p>`,
    },

    el: {
      'faq.q1': `Τι ακριβώς είναι ένα αυτόνομο φωτοβολταϊκό σύστημα;`,
      'faq.q2': `Είναι η αυτόνομη ηλιακή ενέργεια αρκετά αξιόπιστη για μόνιμη διαβίωση;`,
      'faq.q3': `Πώς ξέρω τι μέγεθος συστήματος χρειάζομαι;`,
      'faq.q4': `Τι συμβαίνει τη νύχτα ή σε συνεχόμενες συννεφιασμένες μέρες;`,
      'faq.q5': `Πόσο διαρκούν οι μπαταρίες;`,
      'faq.q6': `Μπορώ να παρακολουθώ και να ελέγχω το σύστημά μου εξ αποστάσεως;`,
      'faq.q7': `Πόσο διαρκεί όλη η διαδικασία — από την πρώτη επαφή έως ένα ενεργό σύστημα;`,
      'faq.q8': `Κάνετε εγκαταστάσεις διεθνώς; Μπορείτε να έρθετε στη χώρα μου;`,
      'faq.q9': `Χρειάζομαι άδεια ή εγκρίσεις για ένα αυτόνομο σύστημα;`,
      'faq.q10': `Πόσο κοστίζει ένα αυτόνομο φωτοβολταϊκό σύστημα;`,
      'faq.q11': `Τι καλύπτει η 7ετής εγγύησή σας;`,
      'faq.q12': `Προσφέρετε χρηματοδότηση ή προγράμματα πληρωμών;`,

      'faq.a1': `<p>Ένα αυτόνομο φωτοβολταϊκό σύστημα είναι μια εντελώς ανεξάρτητη διάταξη ισχύος που παράγει, αποθηκεύει και παρέχει ηλεκτρική ενέργεια ανεξάρτητα από το δίκτυο. Δεν υπάρχει μηνιαίος λογαριασμός ρεύματος, κανένας κίνδυνος διακοπής από βλάβες του δικτύου και καμία εξάρτηση από πάροχο.</p><p>Τα βασικά μέρη είναι: <strong class="text-slate-300">φωτοβολταϊκά πάνελ</strong> που συλλέγουν το ηλιακό φως, μια <strong class="text-slate-300">τράπεζα μπαταριών λιθίου</strong> που αποθηκεύει ενέργεια για τη νύχτα και τις συννεφιασμένες μέρες, ένας <strong class="text-slate-300">ελεγκτής φόρτισης MPPT</strong> που βελτιστοποιεί τη συγκομιδή, και ένας <strong class="text-slate-300">υβριδικός inverter</strong> που μετατρέπει την αποθηκευμένη ενέργεια DC σε τυπικό εναλλασσόμενο ρεύμα AC για τις συσκευές σας.</p><p>Κάθε σύστημα που σχεδιάζουμε είναι μελετημένο να καλύπτει 365 ημέρες τον χρόνο — συμπεριλαμβανομένων των χειμερινών μηνών και συνεχόμενων συννεφιασμένων ημερών — χωρίς καύσιμο ή σύνδεση στο δίκτυο.</p>`,
      'faq.a2': `<p>Ναι — τα συστήματά μας επιτυγχάνουν <strong class="text-slate-300">99,9% μετρημένη διαθεσιμότητα</strong> σε όλο το εγκατεστημένο δυναμικό μας. Εκατοντάδες οικογένειες, αγροκτήματα και επιχειρήσεις παγκοσμίως ζουν εξ ολοκλήρου με τα συστήματά μας χωρίς καμία σύνδεση στο δίκτυο.</p><p>Η αξιοπιστία προέρχεται από τη σωστή διαστασιολόγηση και τον πλεονασμό. Μοντελοποιούμε τα δεδομένα ηλιακής ακτινοβολίας της συγκεκριμένης τοποθεσίας σας (τουλάχιστον 10 ετών) και σχεδιάζουμε τη χωρητικότητα των μπαταριών ώστε να καλύπτει τουλάχιστον 3–5 συνεχόμενες ημέρες μηδενικής ηλιακής παραγωγής, ανάλογα με το γεωγραφικό πλάτος και την εποχή.</p><p>Προαιρετικές εφεδρικές γεννήτριες μπορούν να ενσωματωθούν με λογική αυτόματης εκκίνησης για ακραίες συνθήκες, αν και οι περισσότεροι πελάτες δεν χρειάζεται ποτέ να τις ενεργοποιήσουν.</p>`,
      'faq.a3': `<p>Η διαστασιολόγηση εξαρτάται από τρεις βασικούς παράγοντες: την <strong class="text-slate-300">ημερήσια κατανάλωση ενέργειας</strong> (σε kWh), τη <strong class="text-slate-300">γεωγραφική τοποθεσία</strong> (ώρες αιχμής ηλιοφάνειας) και τις <strong class="text-slate-300">απαιτήσεις φορτίου αιχμής</strong> (τα μέγιστα watt που μπορούν να τραβήξουν όλες οι συσκευές ταυτόχρονα).</p><p>Ενδεικτικά: ένα σύγχρονο σπίτι με 3 υπνοδωμάτια χρειάζεται συνήθως 8–15 kWp πάνελ και 20–40 kWh αποθήκευσης. Ένα μεγάλο αγρόκτημα μπορεί να χρειαστεί 30–60 kWp. Ένα απομακρυσμένο εξοχικό ίσως μόνο 2–5 kWp.</p><p>Με κάθε προσφορά περιλαμβάνουμε μια <strong class="text-slate-300">δωρεάν λεπτομερή ενεργειακή μελέτη και έκθεση διαστασιολόγησης</strong>. Στείλτε μας τα στοιχεία σας μέσω της φόρμας επικοινωνίας και οι μηχανικοί μας θα ετοιμάσουν ακριβή προδιαγραφή εντός 24 ωρών.</p>`,
      'faq.a4': `<p>Τη νύχτα, η <strong class="text-slate-300">τράπεζα μπαταριών λιθίου</strong> αναλαμβάνει απρόσκοπτα — ο inverter συνεχίζει να παρέχει σταθερό ρεύμα AC χωρίς καμία διακοπή. Η μετάβαση είναι στιγμιαία και αόρατη για τις συσκευές σας.</p><p>Τις συννεφιασμένες μέρες, τα πάνελ εξακολουθούν να παράγουν 10–30% της ονομαστικής τους ισχύος (ανάλογα με την πυκνότητα των νεφών). Η μπαταρία καλύπτει το έλλειμμα. Διαστασιολογούμε τη μπαταρία για το χειρότερο εποχικό σενάριο με αυτονομία τουλάχιστον 3 ημερών — δηλαδή 3 πλήρεις ημέρες μηδενικής ηλιακής παραγωγής στο κανονικό επίπεδο κατανάλωσής σας.</p><p>Αν επιλέξετε <strong class="text-slate-300">ενσωματωμένη γεννήτρια</strong>, θα εκκινεί αυτόματα μόνο όταν η στάθμη φόρτισης της μπαταρίας πέσει κάτω από ένα ρυθμιζόμενο όριο (συνήθως 20%), θα τη φορτίζει και θα σβήνει — όλα χωρίς καμία χειροκίνητη παρέμβαση.</p>`,
      'faq.a5': `<p>Χρησιμοποιούμε αποκλειστικά μπαταρίες <strong class="text-slate-300">LiFePO₄ (φωσφορικού σιδήρου λιθίου)</strong> — την ασφαλέστερη και πιο ανθεκτική διαθέσιμη χημεία. Σε τυπικό ημερήσιο κύκλο, οι μπαταρίες αυτές διαρκούν <strong class="text-slate-300">10–15 χρόνια</strong>, με προδιαγραφή 6.000+ πλήρων κύκλων φόρτισης στο 80% της χωρητικότητας.</p><p>Αυτό είναι δραματικά καλύτερο από τις παραδοσιακές μπαταρίες μολύβδου-οξέος (3–5 χρόνια) και ασφαλέστερο από άλλες χημείες λιθίου (χωρίς κίνδυνο θερμικής διαφυγής). Κάθε συστοιχία προέρχεται από κατασκευαστές πρώτης βαθμίδας με ενσωματωμένο Σύστημα Διαχείρισης Μπαταρίας (BMS) που προστατεύει από υπερφόρτιση, υπερεκφόρτιση και ακραίες θερμοκρασίες.</p><p>Οι μπαταρίες καλύπτονται από την ολοκληρωμένη 7ετή εγγύησή μας και συνοδεύονται από εγγύηση απόδοσης κατασκευαστή 10+ ετών.</p>`,
      'faq.a6': `<p>Ναι — κάθε σύστημα περιλαμβάνει μια <strong class="text-slate-300">έξυπνη πλατφόρμα παρακολούθησης</strong> προσβάσιμη από smartphone, tablet ή browser. Βλέπετε σε πραγματικό χρόνο την ηλιακή παραγωγή, τη στάθμη φόρτισης της μπαταρίας, την κατανάλωση φορτίου και ιστορικά δεδομένα από οπουδήποτε στον κόσμο.</p><p>Η <strong class="text-slate-300">πύλη παρακολούθησης</strong> (web + εφαρμογή) μπορεί να στέλνει αυτόματες ειδοποιήσεις μέσω email ή SMS αν κάποια παράμετρος βγει εκτός των φυσιολογικών ορίων.</p><p>Οι μηχανικοί μας έχουν επίσης απομακρυσμένη πρόσβαση διαγνωστικών — μπορούμε να εντοπίσουμε και συχνά να επιλύσουμε προβλήματα χωρίς επίσκεψη στον χώρο, εξοικονομώντας σας χρόνο και κόστος.</p>`,
      'faq.a7': `<p>Το τυπικό χρονοδιάγραμμα από το αρχικό αίτημα έως ένα σύστημα σε λειτουργία είναι <strong class="text-slate-300">6–14 εβδομάδες</strong>, ανάλογα με το μέγεθος και την τοποθεσία. Δείτε πώς αναλύεται:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Εβδομάδα 1–2:</strong> Δωρεάν ανάλυση χώρου, ενεργειακή μελέτη και σχεδιασμός συστήματος</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Εβδομάδα 2–3:</strong> Παράδοση αναλυτικής προσφοράς, αναθεωρήσεις και υπογραφή σύμβασης</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Εβδομάδα 3–8:</strong> Προμήθεια εξοπλισμού και μεταφορά στον χώρο</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Εβδομάδα 8–12:</strong> Εγκατάσταση, θέση σε λειτουργία και παράδοση συστήματος</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span><strong class="text-slate-300">Συνεχώς:</strong> Απομακρυσμένη παρακολούθηση, ετήσιος έλεγχος, ισόβια υποστήριξη</span></li></ul><p>Μικρότερα συστήματα εξοχικών μπορούν να ολοκληρωθούν σε μόλις 4 εβδομάδες. Μεγάλα εμπορικά έργα μπορεί να φτάσουν τις 16–20 εβδομάδες.</p>`,
      'faq.a8': `<p>Ναι — δραστηριοποιούμαστε σε <strong class="text-slate-300">40+ χώρες</strong> μέσω του δικτύου πιστοποιημένων συνεργατών εγκατάστασης. Έχουμε ολοκληρώσει έργα σε έξι ηπείρους, από ορεινές κατοικίες έως νησιωτικά θέρετρα.</p><p>Για τις περισσότερες χώρες αναπτύσσουμε έναν τοπικό πιστοποιημένο συνεργάτη που αναλαμβάνει την επιτόπια εγκατάσταση υπό την άμεση μηχανική μας επίβλεψη. Για σύνθετα ή μεγάλα έργα, οι δικοί μας μηχανικοί ταξιδεύουν στον χώρο για τη θέση σε λειτουργία.</p><p>Διαχειριζόμαστε όλη τη διεθνή εφοδιαστική, τα τελωνειακά έγγραφα και τις απαιτήσεις τοπικής συμμόρφωσης για λογαριασμό σας. Απλώς πείτε μας πού βρίσκεται ο χώρος σας όταν υποβάλλετε το αίτημά σας.</p>`,
      'faq.a9': `<p>Οι απαιτήσεις αδειοδότησης <strong class="text-slate-300">διαφέρουν σημαντικά ανά χώρα, περιοχή και μέγεθος συστήματος</strong>. Σε πολλές δικαιοδοσίες, συστήματα σε στέγη ή έδαφος κάτω από ένα όριο kWp εξαιρούνται από άδεια δόμησης. Μεγαλύτερα συστήματα και επίγειες συστοιχίες πιο συχνά απαιτούν άδειες.</p><p>Ως καθαρά αυτόνομο σύστημα (χωρίς σύνδεση δικτύου), συνήθως αποφεύγετε τους πιο σύνθετους κανονισμούς σύνδεσης στο δίκτυο. Ωστόσο, οι δομικές άδειες για τις βάσεις στήριξης και οι οικοδομικοί κανονισμοί για ηλεκτρικές εγκαταστάσεις εξακολουθούν να ισχύουν στις περισσότερες χώρες.</p><p><strong class="text-slate-300">Αναλαμβάνουμε όλη την έρευνα και την τεκμηρίωση αδειοδότησης ως μέρος της ολοκληρωμένης υπηρεσίας μας «με το κλειδί στο χέρι».</strong> Οι τοπικοί μας συνεργάτες γνωρίζουν τους κανονισμούς των περιοχών τους και η ομάδα μας θα σας καθοδηγήσει σε κάθε απαίτηση που αφορά τον χώρο σας πριν ξεκινήσει οποιαδήποτε εργασία.</p>`,
      'faq.a10': `<p>Το κόστος ποικίλλει σημαντικά ανάλογα με το μέγεθος, τα εξαρτήματα, την τοποθεσία και την πολυπλοκότητα της εγκατάστασης. Δείτε ενδεικτικά εύρη για πλήρως εγκατεστημένα συστήματα «με το κλειδί στο χέρι»:</p><div class="mt-3 space-y-2"><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Απομακρυσμένο εξοχικό (WildPower Kit)</span><span class="text-brand-400 font-bold text-sm">€6,000 – €18,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Κατοικία (HomeBase Pro)</span><span class="text-brand-400 font-bold text-sm">€22,000 – €65,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Αγρόκτημα / Αγροτικό (AgroGrid Elite)</span><span class="text-brand-400 font-bold text-sm">€55,000 – €180,000</span></div><div class="flex items-center justify-between py-2.5 px-4 rounded-xl bg-surface-700/60 border border-white/5"><span class="text-slate-300 text-sm font-medium">Εμπορικό (IndustrialCore)</span><span class="text-brand-400 font-bold text-sm">Από €120,000+</span></div></div><p class="mt-3">Αυτές είναι πλήρεις τιμές «με το κλειδί στο χέρι» που περιλαμβάνουν σχεδιασμό, εξοπλισμό, μεταφορικά, εγκατάσταση, θέση σε λειτουργία και 7ετή εγγύηση. Μια <strong class="text-slate-300">αναλυτική προσφορά είναι πάντα δωρεάν</strong> — υποβάλετε τα στοιχεία σας και οι μηχανικοί μας θα δώσουν ακριβή τιμή για το συγκεκριμένο έργο σας.</p>`,
      'faq.a11': `<p>Η <strong class="text-slate-300">ολοκληρωμένη 7ετής εγγύηση συστήματος</strong> είναι από τις ευρύτερες στον κλάδο. Καλύπτει:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Όλα τα βασικά εξαρτήματα: πάνελ, τράπεζα μπαταριών, inverter/φορτιστή, ελεγκτή φόρτισης</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Όλη την καλωδίωση, τους συνδέσμους και τα υλικά στήριξης</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Την ποιότητα εργασίας εγκατάστασης και θέσης σε λειτουργία</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Λογισμικό, firmware και πρόσβαση στην πλατφόρμα παρακολούθησης</span></li><li class="flex gap-2.5"><i class="fas fa-check text-brand-400 text-[10px] mt-1 flex-shrink-0"></i><span>Απομακρυσμένα διαγνωστικά και επίλυση προβλημάτων χωρίς επιπλέον κόστος</span></li></ul><p class="mt-2">Επιπλέον της εγγύησης συστήματος, τα πάνελ φέρουν <strong class="text-slate-300">25ετή εγγύηση απόδοσης</strong> από τον κατασκευαστή (συνήθως ≥80% απόδοση στο 25ο έτος). Μετά την 7ετή περίοδο εγγύησης, προσφέρουμε προσιτά ετήσια συμβόλαια συντήρησης (O&amp;M) για συνεχή υποστήριξη.</p>`,
      'faq.a12': `<p>Ναι — συνεργαζόμαστε με αρκετούς <strong class="text-slate-300">συνεργάτες χρηματοδότησης πράσινης ενέργειας</strong> ώστε να προσφέρουμε ευέλικτες επιλογές πληρωμής σε πελάτες που πληρούν τις προϋποθέσεις. Ανάλογα με τη χώρα και το μέγεθος του έργου, οι επιλογές μπορεί να περιλαμβάνουν:</p><ul class="space-y-2 mt-2"><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Συμβόλαια τμηματικής πληρωμής (προκαταβολή στην παραγγελία, εξόφληση στη θέση σε λειτουργία)</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Δάνεια πράσινης ενέργειας μέσω συνεργαζόμενων χρηματοπιστωτικών ιδρυμάτων</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Ρυθμίσεις leasing για εμπορικά και αγροτικά έργα</span></li><li class="flex gap-2.5"><i class="fas fa-circle text-brand-400/50 text-[8px] mt-1.5 flex-shrink-0"></i><span>Καθοδήγηση για κρατικές επιχορηγήσεις και προγράμματα επιδοτήσεων στη χώρα σας</span></li></ul><p class="mt-2">Η διαθεσιμότητα χρηματοδότησης ποικίλλει ανά περιοχή. <strong class="text-slate-300">Ρωτήστε για επιλογές χρηματοδότησης όταν υποβάλλετε το αίτημά σας</strong> — η ομάδα μας θα σας ενημερώσει τι είναι διαθέσιμο για την τοποθεσία και την κλίμακα του έργου σας.</p>`,
    },
  };

  for (const lang of ['en', 'ru', 'el']) {
    if (T[lang]) Object.assign(T[lang], faq[lang]);
  }
})();
